import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Card } from '../components/card/Card'
import { getFellows } from '../domain/contentful/service'
import styles from '../styles/Home.module.css'
import styles2 from './index.module.css'

interface HomeProps {
    fellows: Awaited<ReturnType<typeof getFellows>>
}

const Home: NextPage<HomeProps> = ({ fellows }) => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="bg-white">
                <div className="grid grid-cols-4">
                    {fellows.map((fellow) => (
                        <Card
                            title={fellow.name}
                            text={fellow.description}
                            image={fellow.image?.fields.file.url}
                            key={fellow.name}
                        />
                    ))}
                </div>
            </main>

            <footer className={styles.footer}></footer>
        </div>
    )
}

export const getServerSideProps: GetServerSideProps<HomeProps> = async () => {
    return {
        props: {
            fellows: await getFellows(),
        },
    }
}

export default Home
